version: "3.8"

services:
  php-fpm:
    image: php:8.0-fpm-alpine
    container_name: php-fpm
    volumes:
      - ./code:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./code:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
